In [4]:
import numpy as np
import pandas as pd
from datetime import datetime
import re

In [116]:
def seperate_date_time(x, dt):
    dt_format = {
        "12 Hour": "%H:%M %p",
        "24 Hour": "%H:%M"
    }
    date = pd.to_datetime(x.split(', ')[0], format="%m/%d/%y")
#     time = pd.to_datetime(x.split(', ')[1].split(' - ')[0], format=dt_format[dt])
    time = pd.to_datetime(x.split(', ')[1].split(' - ')[0]).strftime('%H:%M %p')
    return date, time

In [117]:
def createDf(file_data, dt):
    patterns = {
        '12 Hour':'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APap][mM]\s-\s',
        '24 Hour':'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s',
    }
    
    data = ' '.join(file_data.read().split('\n'))
    user_message = re.split(patterns[dt], data)[1:]
    date_time = re.findall(patterns[dt], data)
    
    df = pd.DataFrame({'user_message': user_message, 'date_time': date_time})
    df[['date','time']] = df['date_time'].apply(lambda x: seperate_date_time(x, dt)).to_list()
    users = []
    messages = []
    for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1:]:
            users.append(entry[1])
            messages.append(entry[2])
        else:
            users.append('group_notification')
            messages.append(entry[0])

    df['user'] = users
    df['message'] = messages
    df.drop(columns=['user_message', 'date_time'], inplace=True)
    return df

In [118]:
f = open('WhatsApp Chat with Say GT (original) 12 hour format.txt', 'r', encoding='utf-8')
createDf(f, '12 Hour')

,date,time,user,message
0,2022-05-09,15:01 PM,group_notification,Messages and calls are end-to-end encrypted. N...
1,2022-05-26,19:21 PM,Clg Divyansh,Robotics ke notes
2,2022-05-26,19:44 PM,Clg Kushagra Ahire,MST me jo numerical aaye the uske solution bhe...
3,2022-05-26,19:55 PM,Clg Abbas Amjhera,<Media omitted>
4,2022-05-26,20:05 PM,+91 6239 413 783,Bhai notes bhej do yrr koi üôèüèª
...,...,...,...,...
1452,2022-08-18,14:01 PM,Clg Charchil,ü§ö
1453,2022-08-18,14:01 PM,+91 87705 37687,‚úãüèª
1454,2022-08-18,14:15 PM,Clg Atman,üôã‚Äç‚ôÇÔ∏è
1455,2022-08-18,14:20 PM,Clg Ashvin birla,<Media omitted>
1456,2022-08-18,14:56 PM,+91 72409 15291,Sab aadhar card yaa college I'd card saath me ...

In [112]:
f = open('WhatsApp Chat with Say GT (original) 24 hour format.txt', 'r', encoding='utf-8')
pd.DataFrame(createDf(f, '24 Hour'))

,date,time,user,message
0,2022-05-09,15:01:00,group_notification,Messages and calls are end-to-end encrypted. N...
1,2022-05-26,19:21:00,Clg Divyansh,Robotics ke notes
2,2022-05-26,19:44:00,Clg Kushagra Ahire,MST me jo numerical aaye the uske solution bhe...
3,2022-05-26,19:55:00,Clg Abbas Amjhera,<Media omitted>
4,2022-05-26,20:05:00,+91 6239 413 783,Bhai notes bhej do yrr koi üôèüèª
...,...,...,...,...
1437,2022-08-17,14:13:00,Clg Amit Pandey,ni
1438,2022-08-17,14:14:00,+91 87705 37687,Nhi
1439,2022-08-17,14:29:00,Clg Ashvin birla,Hmara to parso paper h
1440,2022-08-17,14:29:00,Clg Ashvin birla,Subh 9 bje
1441,2022-08-17,14:47:00,Clg Kushagra Ahire,Rajavat sir kab tak rehte hai college me?

In [78]:
df['date'].dt.year
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['hour'] = df['time'].dt.hour
df['minute'] = df['time'].dt.minute
df.head()

,date,time,user,message,month,day,hour,minute
0,2022-05-09,1900-01-01 15:01:00,group_notification,Messages and calls are end-to-end encrypted. N...,May,9,15,1
1,2022-05-26,1900-01-01 19:21:00,Clg Divyansh,Robotics ke notes,May,26,19,21
2,2022-05-26,1900-01-01 19:44:00,Clg Kushagra Ahire,MST me jo numerical aaye the uske solution bhe...,May,26,19,44
3,2022-05-26,1900-01-01 19:55:00,Clg Abbas Amjhera,<Media omitted>,May,26,19,55
4,2022-05-26,1900-01-01 20:05:00,+91 6239 413 783,Bhai notes bhej do yrr koi üôèüèª,May,26,20,5

In [66]:
x = '15:30'
x.split(':')[0]

'15'